name: epitech_mirrorer

# version: 1.0.0

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    SOURCE: Hanra-s-work/rtype
    MIRROR_URL: "Hanra-s-work/Rattrapage-promo-2027"
    GITHUB_SSH_KEY: ${{ secrets.MIRROR_KEY }}

jobs:
    test_compilation:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: dump environement
          run: |
            echo "${{secrets.DATABASE_ENV}}" > database/.env
            echo "${{secrets.SERVER_ENV}}" > server/.env

        - name: compile the docker compose
          run: |
            docker compose build

        - name: Start the docker compose
          run: |
            docker compose up -d
        
        - name: Run the tests for the server
          run: |
            docker exec a-server npm run test

    push_to_mirror:
        runs-on: ubuntu-latest
        needs: "test_compilation"
        if: success()
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Push the content to the mirror repository
          uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url: git@github.com:${{ env.MIRROR_URL }}.git
            ssh_private_key: ${{ env.GITHUB_SSH_KEY }}
